# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Pipeline
run-name: Deployed in ${{ github.event.repository.name }}	 # by default its the commit message
env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}
# on: [push, pull_request]
on:
  # # workflow_call:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - name: prebuild job
      run: |
        echo "github.ref_name - ${{ github.ref_name }}"
        echo "github event repo name - ${{ github.event.repository.name }}"
        echo "BRANCH_NAME - $BRANCH_NAME"
        echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
        echo "REPO_NAME - ${REPO_NAME}"

  build:
    # runs-on: ubuntu-latest
    uses: yeeyunjie/my-workflows/.github/workflows/build.yaml@${REPO_NAME}
    # predefined actions are hosted - everyone who uses this will use the checkout command so 
    # created checkout ocmmand to see - actions is actually a repo


    

